
GET http://127.0.0.1:5002/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MjY2MjE4NSwianRpIjoiMDIzYTVkN2YtMGI0Ny00NWRlLTg4NGUtNTcyYWU4M2QxODFlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFkbWluIiwibmJmIjoxNzQyNjYyMTg1LCJjc3JmIjoiNGQ3NDRiN2EtODFkMi00ODkwLWFjZmMtZGE2ZTFmNjAzMzQ5IiwiZXhwIjoxNzQyNjYzMDg1fQ.x3ksOtSLewV7yb6I5uADCAqxbY09tr4qDrTsnagUpuE

